### ISSUE TITLE
yoooooo its cursed

### ISSUE THREAD

**Issue by or0802** [Sammycocobear/PissAddon#1]
Just kidding Its soo funny

**Comment by or0802** [comment]
would you mind if I try and compile it

**Comment by Sammycocobear** [comment]
It's going to be released in the PK site soon. It needs to go under review before it can officially be on the site. Omni is sick currently, so it might be a few days ^^

**Comment by Sammycocobear** [comment]
> would you mind if I try and compile it

It's going to be released in the PK site soon. It needs to go under review before it can officially be on the site. Omni is sick currently, so it might be a few days ^^

**Comment by or0802** [comment]
nice ok nice ;D
